/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { useControls } from "leva";

export function Column({ noAO, ...props }) {
  const { nodes, materials } = useGLTF("models/column.glb");

  const { color, ambientOcclusionMap } = useControls({
    color: "white",
    ambientOcclusionMap: false,
  });
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        geometry={nodes.Column2_Baked.geometry}
        material={materials.Column2_Baked}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      >
        <meshStandardMaterial
          key={ambientOcclusionMap}
          {...materials.Column2_Baked}
          aoMap={
            ambientOcclusionMap ? materials.Column2_Baked.aoMap : undefined
          }
          color={color}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("models/column.glb");
